name: interactivo
description: Aplicación de Reto de ExperTIC, con InterGrupo como empresa mentora
version: 1.0.0

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.15.0
  after_layout: ^1.0.7
  line_icons: ^0.2.0
  carousel_slider: ^1.3.1
  flare_flutter: ^1.7.3
  fl_chart: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/graficos/
    - assets/animaciones/
    - assets/imagenes/iconosAreas/
    - assets/imagenes/logosHabilidades/
    - assets/imagenes/medallas/
    - assets/imagenes/otros/
    - assets/imagenes/podio/